Neotraits failling
the-virtual-brain/tvb-library pull request #93
Opened 2019-07-09 14:01 UTC by gabiflorea10

Python 2 to Python 3 migration.

2019-07-09 14:25 UTC, liadomide requested changes
Please let us validate one more time some of the changes

2019-07-09 14:25 UTC, liadomide commented on tvb/simulator/models/__init__.py
> +#from .Zerlaut import Zerlaut_adaptation_first_order, Zerlaut_adaptation_second_order
Why is this model commented out?

2019-07-09 14:25 UTC, liadomide commented on tvb/simulator/simulator.py
> +from tvb.basic.filters.chain import UIFilter, FilterChain
Is the filters import really needed?

2019-07-09 14:25 UTC, liadomide commented on tvb/datatypes/local_connectivity.py
> +    surface = Attr(field_type=surfaces.CorticalSurface, label="Surface", required=False)
This field should remained Required=True, I see in compute_sparse_matrix() method an AttributeError raised, if missing. As we have the validation of required as parts of traits, we should remove that

2019-07-09 14:25 UTC, liadomide commented on tvb/datatypes/patterns.py
> +    spatial = Attr(field_type=equations.FiniteSupportEquation, label="Spatial Equation", required=False)
I think this should also stay required

2019-07-09 14:25 UTC, liadomide commented on tvb/datatypes/patterns.py
> +    volume = Attr(volumes.Volume, label="Volume", required=False)
Shouldn't this remain required?

2019-07-09 14:25 UTC, liadomide commented on tvb/datatypes/patterns.py
> +    focal_points_volume = NArray(dtype=int, label="Focal points", required=False)
Shouldn't this remain required?

2019-07-09 14:25 UTC, liadomide commented on tvb/datatypes/projections.py
> +        label="surface or region", default=None, required=False)
Shouldn't this remain required?

2019-07-09 14:25 UTC, liadomide commented on tvb/datatypes/projections.py
> +    sensors = Attr(field_type=sensors.SensorsEEG, required=False)
Shouldn't this remain required?

2019-07-09 14:25 UTC, liadomide commented on tvb/datatypes/projections.py
> +    sensors = Attr(field_type=sensors.SensorsMEG, required=False)
Shouldn't this remain required?

2019-07-09 14:25 UTC, liadomide commented on tvb/datatypes/spectral.py
> +        required=False,
I think this should remain required

2019-07-09 14:25 UTC, liadomide commented on tvb/datatypes/time_series.py
> +    sensors = Attr(field_type=sensors.SensorsMEG, required=False)
I think this should stay required

2019-07-16 09:27 UTC, maedoc commented on contrib/simulator/models/wong_wang.py
> +        default=numpy.array([0.3297, ]),
why is this PR changing parameter values on the models?

2019-07-16 09:28 UTC, maedoc commented on tvb/basic/filters/chain.py
> +            if type(self.values[i]) in (str, str):
`if isinstance(self.values[i], str)` please

2019-07-16 09:29 UTC, maedoc commented on tvb/basic/filters/chain.py
> +            if type(value) in (str, str, datetime.datetime):
`if isinstance(value, (str, datetime.datetime))` and likewise elsewhere

2019-07-16 09:30 UTC, maedoc commented on tvb/basic/logger/builder.py
> +        for logger in list(self._loggers.values()):
you should not need a `list` here since `list` would only work on an iterable anyway

2019-07-16 09:31 UTC, maedoc commented on tvb/basic/neotraits/info.py
> +        return {ar_name + ' ' + k: v for k, v in list(ret.items())}
just `for k, v in ret.items()` should be enough, no `list()` required

2019-07-16 09:33 UTC, maedoc commented on tvb/datatypes/connectivity.py
> +                    label = label.decode('ascii')
decoding should be done in an I/O routine, in principle

2019-07-16 09:34 UTC, maedoc commented on tvb/datatypes/cortex.py
> +                orient = self.vertex_normals[:len(cortical_region_mapping)][cortical_region_mapping == k, :]
why is this required?

2019-07-16 09:36 UTC, maedoc commented on tvb/tests/library/basic/neotraits/_attr_test.py
> +Floating-point range generator (IEEE-754-proof)
what is this docstring?

2019-07-16 09:38 UTC, maedoc commented
Please rebase the branch for this PR so we don't see lots of changes which aren't related e.g. the Zerlaut model

2019-07-17 11:03 UTC, maedoc commented
I would really, *really* like to see this PR rebased, and the commit history squashed a bit so that it's somehow a meaningful sequence of commits instead of a bajillion "Python 2 to 3 migration" commits.  I know that's asking for extra work, but consider it would make this huge set of changes more  review able.

2019-07-17 12:12 UTC, liadomide commented
Yes, I agree on the rebase strategy. But that would need a senior at Codemart to help Gabi, as he only days ago started using git. Pls bare with us a bit longer

2019-07-17 12:40 UTC, maedoc commented
Maybe I can do it with him at least partly via screen share, what do you think?

2019-07-17 13:17 UTC, popaula937 commented
Hi, I don't get notifications from this PR but I am currently looking over the changes and will try to help Gabi fix the history before merging.

2019-07-19 07:22 UTC, merged